project:
  type: website
  output-dir: docs

theme: cosmo

website:
  title: "MALLORY J FELDMAN"
  navbar:
    left:
      - href: index.qmd
        text: HOME
      - href: publications.qmd
        text: PUBLICATIONS
      - href: partnerships.qmd
        text: PARTNERSHIPS
      
  
  page-footer:
    left: © 2026 Mallory J. Feldman
    
    
    right: 
      - text: "Commitments"
        href: footer/commitments.qmd
      - text: "License"
        href: footer/license.qmd

format:
    html:
      link-external-newwindow: true