project:
  type: website
  output-dir: docs

website:
  title: "MALLORY J FELDMAN"
  navbar:
    left:
      - href: index.qmd
        text: HOME
      - href: about.qmd
        text: ABOUT
      - href: research.qmd
        text: RESEARCH
      - href: publications.qmd
        text: PUBLICATIONS
      - href: curriculum vitae.qmd
        text: CV
      - href: contact.qmd
        text: CONTACT
      
      
  
  page-footer:
    left: |
      © 2026 Mallory J. Feldman  
      Built with [Quarto](https://quarto.org)
      
    right:
      - href: https://scholar.google.com/scholar?as_sdt=0%2C14&btnG=&hl=en&q=Mallory%20Feldman 
        icon: "google"       # Google Scholar
        aria-label: "Google Scholar"
      - href: https://orcid.org/0000-0003-1051-2088
        icon: "info-circle-fill" # ORCID
        aria-label: "ORCID"
      - href: https://www.researchgate.net/profile/Mallory-Feldman/publications
        icon: "r-square-fill" # ORCID
        aria-label: "ResearchGate"
      - href: https://github.com/MalloryJfeldman
        icon: "github" # ORCID
        aria-label: "GitHub"
      - href: https://osf.io/m324r/
        icon: "openai"
        aria-label: OSF
      - href: https://bsky.app/profile/malloryjfeldman.bsky.social 
        icon: "bluesky"         # Bluesky (use a bird icon)
        aria-label: BlueSky
      - href: https://www.linkedin.com/in/malloryjfeldman/
        icon: "linkedin"     # LinkedIn
        aria-label: LinkedIn


format:
  html:
    theme:
      cosmo