---
title: "Curriculum Vitae"
about:
  template: solana
toc: true
---

See my current academic appointments, education, and teaching experience listed below. 

[Click here to download my full CV](https://docs.google.com/document/d/1MTehANlERjCk7fYqt_nXaR1tqve-KHZMiuJreNzapuI/edit?tab=t.0){.btn .btn-outline-primary .btn-lg}

---

## **Academic Appointments**

#### The Ohio State University (present)

Postdoctoral scholar

## **Education**

#### University of North Carolina at Chapel Hill | Dec 2025

PhD Psychology and Neuroscience, Formal concentration in Quantitative Psychology\
Advisers: Kristen Lindquist, PhD; Keely Muscatell, PhD

#### University of North Carolina at Chapel Hill | Dec 2021

MA Psychology and Neuroscience\
Adviser: Kristen Lindquist, PhD

#### Tufts University | May 2016

BA Psychology; BA Peace and Justice Studies w/concentration in Psychology of Conflict\
Advisers: Sam Sommers, PhD; Dale Bryan

## **Teaching Experience**


#### Social Psychology 

- Instructor of Record (Fall 2022)
- Teaching Assistant (Spring 2019, Spring 2022)

#### Introduction to Psychology 

- Teaching Assistant (Fall 2019, Fall 2020)

